### ISSUE TITLE
Missing python dependency cachecontrol

### ISSUE THREAD

**Issue by nathanal** [flathub/org.inkscape.Inkscape#120]
Reported in https://gitlab.com/inkscape/inkscape/-/issues/3537 

tldr; `File> Import Web Image...` raises the error

```
Traceback (most recent call last):
 File "/app/share/inkscape/extensions/other/clipart/import_web_image.py", line 47, in <module>
   from import_sources import RemoteSource, RemoteFile, RemotePage
 File "/app/share/inkscape/extensions/other/clipart/import_sources.py", line 29, in <module>
   from cachecontrol import CacheControl, CacheControlAdapter
ModuleNotFoundError: No module named 'cachecontrol'
```

Going through https://wiki.inkscape.org/wiki/Release_notes/1.2#Important_changes_for_packagers , this looks like the only missing package :crossed_fingers:

**Comment by nathanal** [comment]
Thanks for the speedy fix!
