### ISSUE TITLE
Missing python module for JPEG export

### ISSUE THREAD

**Issue by jimmac** [flathub/org.inkscape.Inkscape#81]
Inkscape now ships with the ability to export JFIF/JPEG (as odd as it is for vector art, there are valid use cases). Sadly Flathub INkscape will fail doing so because of a missing dependency PIL/pillow.

```
Traceback (most recent call last):
  File "raster_output_jpg.py", line 23, in <module>
    JpegOutput().run()
  File "/app/share/inkscape/extensions/inkex/base.py", line 130, in run
    self.load_raw()
  File "/app/share/inkscape/extensions/inkex/base.py", line 143, in load_raw
    document = self.load(self.file_io)
  File "/app/share/inkscape/extensions/inkex/extensions.py", line 73, in load
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by hfiguiere** [comment]
The build will be out in a couple of hours. Let me know if you still have issues.

**Comment by jimmac** [comment]
Can confirm jpeg export works. Thank you!
